name: Solar System Workflow

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          mkdir -p test-results
          mocha app-test.js --timeout 10000 --reporter mocha-junit-reporter --reporter-options mochaFile=test-results/test-result.xml --exit

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/test-result.xml